### ISSUE TITLE
Opening app without first loading libraries fails

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#27]
When I try to open the application without first loading the libraries the libraries will try to load but then they will stall.

![image](https://user-images.githubusercontent.com/26821843/111358386-83627580-8647-11eb-97d2-f192c4353055.png)

If I load the libraries first everything works fine. 

There isn't an error thrown for this which tips the user off about what they need to do to get the app working. We should probably try to make the auto download work when the app tries to open and throw an error that makes sense if it doesn't.

**Comment by zsteinmetz** [comment]
Thank you, @wincowgerDEV! Can you reproduce this? I can't for a strange reason. I've only ran into that issue so far when I aborted the Shiny app while the libraries still load in the background. To tackle this, I was thinking about adding a loading bar to make this better visible from within the app. Any ideas?

**Comment by zsteinmetz** [comment]
![image](https://user-images.githubusercontent.com/10266826/111471251-01e31400-8729-11eb-86db-56a33b700f00.png)

It now looks like this at startup.

**Comment by wincowgerDEV** [comment]
Nice work! That fixed the problem. The bug is no longer present.
