### ISSUE TITLE
Keeping Shiny App Functional While Integrating with GIT

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#3]
I recently made some changes to the Shiny app so that I could pull down the whole repository (with your updates) and automatically run the shiny app on my desktop so that I can keep all developments in this repository. If I should be doing anything differently let me know. @zsteinmetz 

I think we need to add in a call to the shiny app so that it is pulling down the functions that you are developing as add ons, for now I added them into the application. 

I am unsure of what the OpenSpecy Library call in the shiny app will do, it was throwing an error so I hashed it out.

**Comment by zsteinmetz** [comment]
Okay, deploying to shinyapps.io now works as well!

**Comment by wincowgerDEV** [comment]
I think once we get the app deployed to your schools server we will make a
redirect from the current shinyapps.io website to your school server so we
won't need to worry about any of the dependencies for shinyapps.io at that
point.
