### ISSUE TITLE
Pushing Open Specy to shinyapps.io resulted in error

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#35]
Could not find function adj_intens

[logs (3).txt](https://github.com/wincowgerDEV/OpenSpecy/files/6190054/logs.3.txt)

GUI displayed this message:
![image](https://user-images.githubusercontent.com/26821843/112156032-1dc03d00-8ba3-11eb-9c78-5417ec6e14e5.png)

Probably due to not updating the functions on my desktop before pushing to shiny.io.

Retrying now.

**Comment by zsteinmetz** [comment]
> Probably due to not updating the functions on my desktop before pushing to shiny.io.

Most likely. Try to reinstall from the current rc branch before using

```r
devtools::install_github("wincowgerDEV/OpenSpecy@rc")
```

**Comment by zsteinmetz** [comment]
From the logs, I also see that the library download was triggered. Did you add the .rds files to `/data` or does the automatic recognition failed? Currently, the library will be downloaded again each time the app is woken up.

**Comment by wincowgerDEV** [comment]
It worked :) Thanks. It seems like the library only gets downloaded one time though. I tried refreshing in the new session and it didn't redownload the libraries. I didn't add the rds files to /data, I let shiny pull them from osf when it started up and it seemed to work fine.

**Comment by zsteinmetz** [comment]
Wait until the app goes to sleep and is woken up by some user. Guess, this will trigger a new download (or maybe it just did with my free shinyapps.io version).

Does the dropbox integration work?

**Comment by wincowgerDEV** [comment]
I'll try that out and see if we can fix it. Probably the best fix is to
just add the rda files before upload like you suggested.

**Comment by zsteinmetz** [comment]
Seems like it works (at least locally):

```
File /tmp/Rtmp4Ud1z5/20210323-154320_66a8fb1c0f359bee4b12a565b18c88e4.csv uploaded as /Spectra/20210323-154320_66a8fb1c0f359bee4b12a565b18c88e4.csv successfully at 2021-03-23T14:43:21Z
File /tmp/Rtmp4Ud1z5/20210323-154320_66a8fb1c0f359bee4b12a565b18c88e4_form.csv uploaded as /Spectra/20210323-154320_66a8fb1c0f359bee4b12a565b18c88e4_form.csv successfully at 2021-03-23T14:43:23Z
```

Just realized though that the data won't save in a separate folder anymore. Bad?

**Comment by wincowgerDEV** [comment]
We may want to overhaul the data upload schema one final time to get it
somewhere where it does everything we want with the least effort.

**Comment by zsteinmetz** [comment]
What do you have in mind?

**Comment by wincowgerDEV** [comment]
I'll need to shift focus to getting the manuscript edits to all co-authors
for the next week or so but definitely circling back to this before we
finalize the paper.

Happy to bounce some ideas off for now. I think we need to link the key to
the original dataset upload through all data and metadata names. Probably
remove the file nesting because it makes it tedious. Also might want to
track all the user clicks while they are using the tool and bundle that up
into a file that gets saved with the same uploaded file name. Also might
want to set up the data stashing you suggested where the data gets stashed
in a temporary folder and then gets upload asynchronously. Or maybe upload
at next open. May also want to integrate a nosql server long mongodb.
