### ISSUE TITLE
Share metadata failing

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#36]
When I try to share metadata with the new app on shiny.io the app crashes and doesn't return an error message in the logs. 

![image](https://user-images.githubusercontent.com/26821843/112158442-67aa2280-8ba5-11eb-9ba0-b01aebbdacd9.png)

**Comment by wincowgerDEV** [comment]
When I run the app locally I get this warning:
Warning: Error in : Can't modify read-only reactive value 'share_decision'

**Comment by zsteinmetz** [comment]
I see. I'll have a look.

**Comment by zsteinmetz** [comment]
This line is the culprit:

https://github.com/wincowgerDEV/OpenSpecy/blob/aa9ddddad252a0892a56b3fdc61810c4944451d8/inst/shiny/server.R#L90

My bad. Don't know how it got there :roll_eyes: 

I'll push a fix for you to try on shinyapps.io
