### ISSUE TITLE
license type

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#39]
Thinking about whether CC BY NC or CC by is more appropriate for the Open Specy code and libraries. 

It looks like we can use any of these licenses for CRAN submission:
https://svn.r-project.org/R/trunk/share/licenses/license.db

CC BY NC is allowed. 

I think the original idea I had was to limit the risk of corporations taking the Open Specy code and commercializing it. There will likely be a myriad of licenses for the data and I need to do a better job of documenting which datasets have which license. That reminds me that we recently got some data which the people are ok with us using on the website but not with sharing. We need to make some new functionality to accommodate for that. Let me know your thoughts on this matter. I am leaning toward making the source code CC BY 4.0, making the data people upload CC BY NC (by default but we hold the license so we can always make it less restrictive when we want to), and making the data in the library whatever license the sharer wants it to be.

**Comment by zsteinmetz** [comment]
I don't know how good it is to change the license too often. Everything published until now would be under a different license than the new code/spectra added. Therefore, I'd definitely stick with CC BY for the code.

When it comes to metadata and spectra, why not letting the user chose the license with an extra dropdown menu (at least for metadata and associated spectra). 
For spectra only, I'd go with something simple: CC0, CC-BY or CC-BY-NC .. whichever you prefer. In the end, it'll come down to how open/permissive you want the data to be.

**Comment by wincowgerDEV** [comment]
Thanks for this great input. It's awesome to be able to bounce these ideas
off someone who knows stuff about this. I agree about the metadata license
input. Great idea! I think we will stay with cc by nc for the uploaded data
for now too since that is what people are familiar with.

**Comment by zsteinmetz** [comment]
I won't have time to start coding before Monday but I opened up a new branch already as a reminder.

**Comment by wincowgerDEV** [comment]
Me either but I'll be joining the final development on Monday with you.
Have a great weekend.

Win
