### ISSUE TITLE
Share spectra not inclusive for raw data saving

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#47]
I want users to be able to save and share their data in the raw form that they upload it in. Previous versions used to allow for that but now it seems like we have moved away from that in favor of standardizing the data format?

https://github.com/wincowgerDEV/OpenSpecy/blob/b3358475bd26f762a1993c28ccab107caab61fe4/R/share_spec.R#L102

I might be reading into this wrong. Let me know if so, @zsteinmetz

**Comment by zsteinmetz** [comment]
Oh, sorry for that! I was not perfectly sure how you wanted it to be when I coded the new functions. So what would be your ideal workflow?

1. User uploads spectrum
2. Original file is shared via dropbox
3. If metadata is filled and submitted, metadata is added to the dropbox folder where the original data has been saved previously.

What's the advantage of saving original files over a standardized csv file? From the R package workflow, it would indeed make more sense to work with standardized data once its read. But we can easily change that, no problem.

**Comment by wincowgerDEV** [comment]
No worries. 

The advantage of saving the original file is that in some files (spa, spc, jdx) there is extra metadata that we can mine about the spectrum (instrument information, preprocessing information, and other goodies). Another advantage is that if we have a bug in our file reading or file conversion, it won't impact their data. 

We can always also save a copy in a standardized format too, but I want to make sure we have the raw data backed up. 

The workflow I was thinking of is:
1. User uploads spectrum, if(share ==T) then a copy of the spectrum in its original form gets backed up. 
2. A file upload triggers tracking of the users clicks. if(share ==T) any clicks that the user makes will get logged and matched to that spectrum using a key.
3. If the user chooses to input metadata into our form and clicks share, a formatted metadata file gets saved that matches the spectrum via a key. 
4. All of this data gets stored on dropbox in one folder that links to the user's cookie id or on the users desktop, depending on the mode they have selected. 
5. We build out an information retrieval routine that improves the UI by remembering the user's last sections when they log back on and allows them to query their own previously uploaded datasets.

**Comment by zsteinmetz** [comment]
> Starting to wonder if we should actually even have the share spectra function. We probably won't be able to give people the drop token, so functions like this will only work for us to use when we push online. Maybe we should remove it from the package as it may be misleading right now?

Yeah, you're right. My intention was to have a generic function that can both feed a remote dropbox folder (if a token is available on a hosted server) or some other decentralized sharing method (which is currently missing). In it's current state, package users can use `share_spectrum()` to generate standardized metadata csv files for sharing via e-mail. For now, we could make this more transparent with message outputs rather than making the whole function defunct. I'll try to think that through further and start working on it next week.
