### ISSUE TITLE
Numbers missing from sliders

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#48]
Just realized today that the numbers on the sliders somehow got grayed out, not sure if it was from the theme update. 

![image](https://user-images.githubusercontent.com/26821843/113086234-1f3ac800-9196-11eb-8503-7caa7e90cc90.png)

Isn't that big of a deal, maybe we just remove them altogether since the number on top of the slider already indicates what you need to know?

**Comment by wincowgerDEV** [comment]
Agreed, enhancement is more appropriate here :). It took me a while to notice too. I don't think it is a very critical issue.

**Comment by zsteinmetz** [comment]
Fixed with #54.
