### ISSUE TITLE
Interface graph axes

### ISSUE THREAD

**Issue by paloeffler** [wincowgerDEV/OpenSpecy#49]
Absorbance spectra, when given in wavenumbers, are usually labeled from high (left) to low (right) numbers on the x-axis. This is to prevent misunderstandings, because a higher wavenumber means lower wavelength or frequency. In the displayed manner high wavenumber could lead to the assumption of a high wavelength or frequency.

**Comment by zsteinmetz** [comment]
Good point! What's your take on this @wincowgerDEV?

**Comment by wincowgerDEV** [comment]
@paloeffler we really appreciate the comment. I agree with you that it is more readily interpretable to have wavenumbers be ordered in the way you suggested. The whole use of wavenumbers (the number of that size of waves that could fit into a centimeter) is a strange metric but is the standard for spectroscopy. I looked into some of the other software I have and they default to the form you suggest. Let's make it happen. We can always add reversing the order back to what it is now as an advanced feature too. We will get this updated by the time we do the next CRAN push and should have the GitHub version updated in the next week or so. 

@zsteinmetz looks like there are some simple ways to reverse the axes: https://plotly.com/r/axes/#reversed-axes

Warm Regards, 
Win

**Comment by zsteinmetz** [comment]
> @zsteinmetz looks like there are some simple ways to reverse the axes: https://plotly.com/r/axes/#reversed-axes

Yep, shouldn't be a big deal. I can take care of it.

**Comment by zsteinmetz** [comment]
Note @wincowgerDEV that we'll also need to change the vignette screenshots accordingly sooner or later

**Comment by wincowgerDEV** [comment]
Good point! I'll do that once we push the update.
