### ISSUE TITLE
adj_intens will not return km transformation. 

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#52]
I recently realized that the km transformation (reflectance) isn't working in the adj_intens function. 

reproducible example:

`library(OpenSpecy)
data("raman_hdpe")
head(adj_intens(raman_hdpe, type = "reflectance"))
head(adj_intens(raman_hdpe, type = "none"))
`

The two datasets should be the inverse of one another but they produce very slightly altered versions of the same thing. 

However, transmittance seems to be working fine.

**Comment by wincowgerDEV** [comment]
`(1 - adj_neg(y))^2 / (2 * adj_neg(y)),`

The km function in the adj_intens seems to be correct.

**Comment by wincowgerDEV** [comment]
`y <- raman_hdpe$intensity 

(1 - adj_neg(y))^2 / (2 * adj_neg(y)) == y`

When I run it by itself, it seems to work.

**Comment by wincowgerDEV** [comment]
When I plot the two, they overlap so much we cant see the one on top of the other though. 
![image](https://user-images.githubusercontent.com/26821843/113354894-c0d82b80-92f4-11eb-81e3-34af3cee7e23.png)

A typical transformation should look like this. 
![image](https://user-images.githubusercontent.com/26821843/113354958-dea59080-92f4-11eb-9eeb-2ceb2d6c82ef.png)
![image](https://user-images.githubusercontent.com/26821843/113354999-f250f700-92f4-11eb-9268-078d7cd44274.png)

**Comment by wincowgerDEV** [comment]
This almost works 

`(1 - make_rel(adj_neg(y)))^2 / (2 * make_rel(adj_neg(y)))`

The problem was that the function assumes a percent. That is why it subtracts 1. 

But then I get an INF value.

**Comment by wincowgerDEV** [comment]
The inf value is coming from the bottom of the division when the lowest value is created. I going to check how I dealt with this in the original version.

**Comment by wincowgerDEV** [comment]
Seems like it wasn't working correctly before either unless people uploaded a percent reflectance file formatted as a decimal percent. We should clarify this in the tool. 

Now we are talking. I put this through with a real percent reflectance spectrum. 

`make_rel((1 - reflectance$intensity/100)^2 / (2 * reflectance$intensity/100))`
![image](https://user-images.githubusercontent.com/26821843/113359206-27147c80-92fc-11eb-8d23-88f9b23010ee.png)

The above function assumes that their data is formatted as a percent in 100 and corrects for the function. I will add this to the documentation.

**Comment by zsteinmetz** [comment]
Thanks for all your efforts and tracking down that bug! What speaks against giving more flexibility to the user and allowing the user to supply intensity values either as percentage or decimal numbers? Accepting only percentages here is somehow inconsistent with our approach to normalized all intensity data to values between 0 and 1.

**Comment by wincowgerDEV** [comment]
The km function assumes that the data is an absolute percent (not scaled
between zero and one with zero being the lowest measurement and one being
the highest). I think we could allow decimal absolute percents in addition
to 1-100, I just couldn't figure out the test. If we test using the numbers
(e.g. if(max(x)>1)) how do we know that they didn't just have really low
reflectance percent values from 1-100? It would be better to access the
metadata in the spectra files and interpret it that way. But I haven't
figured out how to do that yet. We could also allow them to specify what
range their percent are in, but then we would have to add yet another
selection option.

**Comment by zsteinmetz** [comment]
What about converting all values to decimals using the helper functions in data_norm.R before applying the KM equation?

**Comment by wincowgerDEV** [comment]
That might work. I will test if it produced the same output.

Win

**Comment by wincowgerDEV** [comment]
It won't work to normalize the data first because a zero gets created which makes the function create "inf". Also if we ignore the zero by filtering it out, the signature at the end is still not very similar (likely because the relative transformation stretches things out. 

Dots = data, black line = current transformation, red line = normalize first transformation. 
 
![image](https://user-images.githubusercontent.com/26821843/113744047-2f343980-96b9-11eb-9659-55b1750d07e4.png)

reproducible fig:
`
library(OpenSpecy)
library(dplyr)
library(ggplot2)

FTIR <- read_spa(read_extdata("ftir_polyethylene_reflectance_adjustment_not_working.spa"))

FTIR %>%
    mutate(intensity1 = OpenSpecy::make_rel(intensity)) %>%
    mutate(intensity2 = make_rel((1 - intensity/100)^2 / (2 * intensity/100))) %>%
    filter(intensity1 > 0) %>%
    mutate(intensity3 = make_rel((1 - intensity1)^2 / (2 * intensity1))) %>%
    ggplot() + geom_point(aes(x = wavenumber, y = intensity1)) + geom_line(aes(x = wavenumber, y = intensity3), color = "red") + geom_line(aes(x = wavenumber, y = intensity2))


test <- FTIR %>%
    mutate(intensity1 = OpenSpecy::make_rel(intensity)) %>%
    mutate(intensity2 = make_rel((1 - intensity/100)^2 / (2 * intensity/100))) %>%
    mutate(intensity3 = make_rel((1 - intensity1)^2 / (2 * intensity1)))

test$intensity2 == test$intensity3`

**Comment by wincowgerDEV** [comment]
Let me know if you have any other ideas @zsteinmetz, otherwise, we can keep the function the way it is for now. 

Win

**Comment by zsteinmetz** [comment]
I agree
