### ISSUE TITLE
Exclusive sharing via dropbox

### ISSUE THREAD

**Issue by zsteinmetz** [wincowgerDEV/OpenSpecy#55]
With #46, this bit of code

https://github.com/wincowgerDEV/OpenSpecy/blob/3f6922d88f66de37a269dc5033fd1a6c486508e1/inst/shiny/server.R#L132-L139

changed from a generic way of sharing spectra to relying exclusively on Dropbox and bypassing the config.yml. Should we keep it this way?

I'd rather argue in favor of keeping the package functions the heart of the Shiny app and using them whenever possible. I agree that this is challenging when it comes to spectra sharing but I guess it's still possible if the `share_spec` function allows for (1) preparing files the way we would like them to receive and (2) provide interfaces to share those via e-mail (for package users) or dropbox (if hosted). In my opinion, this should not be too complicated.

If you agree, I could make the necessary changes with one of the next PRs.

**Comment by wincowgerDEV** [comment]
Yeah! I agree, it would be an improvement to incorporate this into the share_spec function. I just couldn't figure out how to do it so I made this workaround.

**Comment by zsteinmetz** [comment]
Alright. I'll free up some time for it this week. This will probably also fix #47.

**Comment by wincowgerDEV** [comment]
Thanks ☺️

**Comment by zsteinmetz** [comment]
Fixed with #54
