### ISSUE TITLE
Create a forum where people can talk about spectra and matches from the app. 

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#79]
I want to have a discussion forum where people can post their spectra and ask for input about whether they have processed it correctly/identified it correctly. In microplastic research, we have so many new practitioners who are just getting started and often don't have the mentorship to figure out how best to ID their spectra and clean them. This forum will hope to solve that problem. I already have a few people in mind for Admins that have gotten in contact in the past. 

This could be on the OS webpage as a new tab/popup on the identification tab. It could also be an entirely separate forum location. It would be nice if whatever we use could somehow be plugged into people's email addresses so that they get an email when someone responds to their comment so we don't lose the threads as often. 

Any ideas @zsteinmetz or @ardcarvalho?

**Comment by zsteinmetz** [comment]
I like the idea. Maybe this would be a good opportunity to pull some contents out of the current Shiny app and build a nice website around it. With a decent CMS, such a forum shouldn't be a big deal.

**Comment by wincowgerDEV** [comment]
Any feelings about something like this: https://github.com/gitalk/gitalk

We could also just go with slack. Pretty much anything we do is going to require the user to login with some account.

**Comment by wincowgerDEV** [comment]
This is another option that might work: https://docs.github.com/en/discussions

**Comment by wincowgerDEV** [comment]
I just enabled GitHub discussions:
https://github.com/wincowgerDEV/OpenSpecy/discussions

This might help us out.

**Comment by wincowgerDEV** [comment]
Yeah, that seems to be doing everything I would want it to. Let me know what you think @zsteinmetz maybe we can change the email and issues suggestions to move people toward using this discussions tool.

**Comment by zsteinmetz** [comment]
Ahh nice! Didn't know that GitHub already has a forum built in. This should do perfectly fine!
