### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#8]
How should we make sure that people know how to cite the package? I think we will want the publication that we are working on to eventually be the citation for the package but for now, it can just be what is on the website, plus adding @zsteinmetz as an author? Once the publication is out then we can update the citation with the manuscript citation?

**Comment by zsteinmetz** [comment]
Totally forgot about this. Feel free to continue working on this branch as you see fit. Where do you think should my name go in the Shiny UI citation?

**Comment by wincowgerDEV** [comment]
Where would you like your name to go? I feel like you have done the most
work on this tool after me so you can be anything besides the first author.
I know some institutions have different weight that they put on specific
author positions so whatever helps you look the best is cool with me.
