### ISSUE TITLE
Switches/check boxes for preprocess tab

### ISSUE THREAD

**Issue by zsteinmetz** [wincowgerDEV/OpenSpecy#9]
I'm currently struggling with making this bit of code work with the new functions:

https://github.com/wincowgerDEV/OpenSpecy/blob/bde5f109207940dac1985313a3838ba0f1b4810f/inst/shiny/server.R#L205-L221

This is mainly because of the nested if statements and function logic being inconsistent with the UI: A smoother of `p = 0` or a background substration with `degree = 0` are not the same as no smoothing/subtraction. Would it make sense to add some switches/check boxes to the tab to toggle each filter on and off?

**Comment by zsteinmetz** [comment]
It's not beautiful but works.

**Comment by wincowgerDEV** [comment]
I agree that the p=0 and degree = 0 workaround I made was not elegant. I think having a switch to totally remove the smoothing or background subtraction or range selection would be ideal.

**Comment by zsteinmetz** [comment]
![image](https://user-images.githubusercontent.com/10266826/111333244-cd148580-8672-11eb-8411-0eb7b1d06ecd.png)

Maybe something like this?

**Comment by zsteinmetz** [comment]
> We could have the check box either completely hide the slider or just gray it out.

Good idea!

**Comment by wincowgerDEV** [comment]
This feature has been added with https://github.com/wincowgerDEV/OpenSpecy/pull/28#issue-595933594
