### ISSUE TITLE
Create funding goals bar which highlights where we are at and what our goals are

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy#98]
Dying: 0-100$ the application will cease to be hosted online and maintenance will stop.
Life support: 100-1000$ per year just to keep the shiny app online and essential maintenance.
Doing alright: 1k-10k$ per year for maintenance costs and minor ad-hoc updates and bug fixes (***I think this is where we are at right now)
Sustaining: 10k - 100k$ per year for having a single part-time to full-time staff person working to update and build the community and the tool. (we will be here soon once I start with the Moore institute since they will be funding my time at roughly 10% to work on this which is about the minimum).
Revolutionizing the field: 100k-1mill$ per year to have a team that is constantly pushing the science and tool closer to the ultimate goal of 100% accurate spectral identification and deep spectral diagnostics with a single click.

**Comment by zsteinmetz** [comment]
That's a great idea!
